"""Deterministically embed the additive module and generate its strategy twin.

Only marked blocks and the strategy declaration/adapter differ. --check does
not write. This is a mechanical source build, not a Pine compiler.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / 'indicator-based-version1.pine'
STRATEGY = ROOT / 'indicator-based-version1-backtest.pine'


def function_block(source, name):
    lines = source.splitlines(keepends=True)
    start = next(i for i, line in enumerate(lines) if line.startswith(name + '('))
    end = start + 1
    while end < len(lines) and (not lines[end].strip() or lines[end].startswith((' ', '//'))):
        end += 1
    return ''.join(lines[start:end]).rstrip() + '\n\n'


def contract_fixture():
    types = (ROOT / 'modules/smart_trade_types.pine').read_text()
    engine = (ROOT / 'modules/smart_trade_engine.pine').read_text()
    prefix = '''//@version=5
indicator("Smart Trade Contract Tests", overlay=true)
// Generated from the production modules: do not edit this file.
st_risk = 10.0
st_pip = 0.1
st_cost_pips = 4.0
st_stop_model = 'Fixed 100 pips'
st_min_stop_pips = 20.0
st_max_stop_pips = 500.0
st_stop_buffer = 0.5
st_target_buffer = 0.2
st_merge = 0.5
st_chase_r = 0.75
st_risk_cash = 100000.0
st_qty_step = 0.001
st_target_mode = 'Structure'
st_stop_mode = 'Fixed original stop'
st_expiry = 240
st_confirm_window = 12
st_confirmation_anchor = 'Internal swing'
'''
    prefix += types[types.index('type STZone'):types.index('st_register(')]
    for name in ['st_target_pair', 'st_plan', 'st_prepare_trade_bar', 'st_trade_risk', 'st_cost_r', 'st_process_point', 'st_step_zone', 'st_zone_confirmable']:
        prefix += function_block(engine, name)
    return prefix + (ROOT / 'tests/contract_cases.pine').read_text()


def embedded(source, name, content):
    start, end = f'// BEGIN SMART TRADE {name}', f'// END SMART TRADE {name}'
    replacement = f'{start}\n{content.rstrip()}\n{end}'
    pattern = re.escape(start) + r'.*?' + re.escape(end)
    result, count = re.subn(pattern, lambda _: replacement, source, flags=re.S)
    if count != 1:
        raise ValueError(f'Expected exactly one {name} block, found {count}')
    return result


def build():
    source = MAIN.read_text()
    for name, filename in [('TYPES', 'smart_trade_types.pine'), ('ENGINE', 'smart_trade_engine.pine')]:
        source = embedded(source, name, (ROOT / 'modules' / filename).read_text())
    indicator = embedded(source, 'EXECUTION', '// Indicator only: the research ledger above is not a broker fill report.')
    declaration = '''strategy(title = "SMC & ICT + Smart Trade Research Strategy"
  , overlay = true, max_labels_count = 500, max_lines_count = 500
  , max_boxes_count = 500, max_bars_back = 5000, pyramiding = 0
  , initial_capital = 100000, default_qty_type = strategy.fixed
  , commission_type = strategy.commission.percent, commission_value = 0
  , slippage = 0, process_orders_on_close = true
  , calc_on_order_fills = false, calc_on_every_tick = false
  , use_bar_magnifier = false, margin_long = 100, margin_short = 100)'''
    strategy, count = re.subn(r'indicator\(title = .*?max_bars_back = 5000\)', declaration, indicator, count=1, flags=re.S)
    if count != 1:
        raise ValueError('Indicator declaration not found')
    strategy = embedded(strategy, 'EXECUTION', (ROOT / 'modules' / 'smart_trade_execution.pine').read_text())
    return {MAIN: indicator, STRATEGY: strategy, ROOT / 'tests/smart_trade_contract.pine': contract_fixture()}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, expected in build().items():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                raise SystemExit(f'Out of sync: {path.name}')
            print(f'In sync: {path.name}')
        else:
            path.write_text(expected)
            print(f'Built: {path.name}')
